global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using $ext_safeprojectname$.Common.StringTools;
global using $ext_safeprojectname$.Domain.Core.Bases.Entities;
global using $ext_safeprojectname$.Infrastructure.Data.SqlServer.EfCore.Tools;
global using System;
global using System.Linq;
global using System.Reflection;
global using System.Threading;
global using System.Threading.Tasks;
global using $ext_safeprojectname$.Common;
global using $ext_safeprojectname$.Domain.Core.Bases;
global using $ext_safeprojectname$.Domain.Core.Bases.Repositories;
global using $ext_safeprojectname$.Infrastructure.Data.SqlServer.EfCore.Context;
global using System.Collections.Generic;
global using System.Linq.Expressions;
global using $ext_safeprojectname$.Domain.Core.DILifeTimesType;
global using $ext_safeprojectname$.Common.ExceptionTools;
global using System.Data;
global using $ext_safeprojectname$.Infrastructure.Data.Bases;
global using $ext_safeprojectname$.Infrastructure.Data.SqlServer.Dapper.Context;
global using Newtonsoft.Json;
global using Dapper;
global using Autofac;
global using MediatR;


